const students=[

    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'jodu',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'kodu',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Rashida Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'Mojid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Ruhul Amin',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"Arts",
        roll:"35",
    },
    {
        name:'monika',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Halima',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'Bristi Akter',
        class:"10",
        section:"Science",
        roll:"1",
    },
    {
        name:'Suborna',
        class:"10",
        section:"Science",
        roll:"5",
    },
    {
        name:'sumona Akter',
        class:"9",
        section:"Science",
        roll:"13",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    {
        name:'abdul Hamid',
        class:"6",
        section:"A",
        roll:"35",
    },
    
    
 ]
export default students;
